"""Reading a Stripe webhook body -- only ever AFTER its signature has been verified.

Nothing in this module checks a signature, and nothing here may be called on a
body that has not passed aura_web.routes.stripe_webhook's verification. Its job
is narrower: turn a verified body into the three facts the sync needs -- the
event's ID (for idempotency), its type, and which subscription it concerns --
and refuse anything malformed.

The event's own contents are deliberately NOT used as subscription state.
Stripe delivers events at least once and in no guaranteed order, and its event
timestamps are whole seconds that distinct events share; applying an event's
snapshot could let an older event land after a newer one and win. Every
handled event is therefore only a signal to fetch the subscription from Stripe
and store what it says now (aura_web.billing_sync).
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any

from aura_web.stripe_api import is_stripe_id

# Every event after which a subscription's standing can have changed. Each one
# triggers the same thing -- a fresh fetch of the subscription -- so listing an
# extra one costs a fetch, and missing one costs a stale plan until the next
# event or reconciliation. The invoice events are here for the case the
# subscription's own status does not show: a delayed payment method failing
# after activation voids the invoice while the subscription stays `active`.
HANDLED_EVENT_TYPES = frozenset(
    {
        "checkout.session.completed",
        "checkout.session.async_payment_succeeded",
        "checkout.session.async_payment_failed",
        "customer.subscription.created",
        "customer.subscription.updated",
        "customer.subscription.deleted",
        "customer.subscription.paused",
        "customer.subscription.resumed",
        "invoice.paid",
        "invoice.payment_failed",
        "invoice.payment_action_required",
        "invoice.voided",
        "invoice.marked_uncollectible",
    }
)

_EVENT_TYPE = re.compile(r"^[a-z_]{1,50}(\.[a-z_]{1,50}){1,4}$")


class InvalidEventError(Exception):
    """A verified body that is still not a usable Stripe event."""


@dataclass(frozen=True)
class VerifiedEvent:
    """The parts of a verified Stripe event the sync acts on."""

    event_id: str
    event_type: str
    livemode: bool
    # None when the event is not handled, or concerns no subscription (a
    # one-time payment checkout, an invoice not generated by a subscription).
    subscription_id: str | None


def _reject_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate key {key!r}")
        result[key] = value
    return result


def _reject_constant(name: str) -> Any:
    raise ValueError(f"non-standard JSON constant {name}")


def _subscription_reference(value: object) -> str | None:
    if isinstance(value, dict):
        value = value.get("id")
    if is_stripe_id(value, "sub"):
        return value
    return None


def subscription_id_for(event_type: str, data_object: dict[str, Any]) -> str | None:
    """Which subscription a handled event concerns, from the object shape its type implies.

    Parameters
    ----------
    event_type
        The Stripe event type, which implies the shape of its data object.
    data_object
        The event's ``data.object``.

    Returns
    -------
    str or None
        The subscription the event concerns, or None when the object does not
        carry one in the shape this type implies -- which the caller treats as
        'nothing to sync', never as an error.
    """
    if event_type.startswith("checkout.session."):
        if (
            data_object.get("object") != "checkout.session"
            or data_object.get("mode") != "subscription"
        ):
            return None
        return _subscription_reference(data_object.get("subscription"))
    if event_type.startswith("customer.subscription."):
        if data_object.get("object") != "subscription":
            return None
        return _subscription_reference(data_object.get("id"))
    if event_type.startswith("invoice."):
        if data_object.get("object") != "invoice":
            return None
        parent = data_object.get("parent")
        if isinstance(parent, dict):
            details = parent.get("subscription_details")
            if isinstance(details, dict):
                return _subscription_reference(details.get("subscription"))
            return None
        # Webhook endpoints pinned to an API version before 2025-03-31.basil
        # still send the subscription at the top level of an invoice.
        return _subscription_reference(data_object.get("subscription"))
    return None


def parse_verified_event(payload: bytes) -> VerifiedEvent:
    """Parse a body whose Stripe-Signature has ALREADY been verified.

    Parameters
    ----------
    payload
        The raw request body, whose Stripe-Signature has ALREADY been verified
        by the caller. Parsing an unverified body here would make this function
        a way to feed arbitrary JSON into the sync path.

    Returns
    -------
    VerifiedEvent
        The event's ID, type, livemode flag and data object.

    Raises
    ------
    StripeEventError
        If the body is not a JSON object or is missing a field the caller
        needs.
    """
    try:
        event = json.loads(
            payload.decode("utf-8"),
            object_pairs_hook=_reject_duplicate_keys,
            parse_constant=_reject_constant,
        )
    except (UnicodeDecodeError, ValueError, RecursionError) as exc:
        raise InvalidEventError("the webhook body is not a JSON object") from exc
    if not isinstance(event, dict) or event.get("object") != "event":
        raise InvalidEventError("the webhook body is not a Stripe event")

    event_id = event.get("id")
    event_type = event.get("type")
    livemode = event.get("livemode")
    if not is_stripe_id(event_id, "evt"):
        raise InvalidEventError("the event has no usable id")
    if not isinstance(event_type, str) or _EVENT_TYPE.match(event_type) is None:
        raise InvalidEventError("the event has no usable type")
    if not isinstance(livemode, bool):
        raise InvalidEventError("the event has no livemode flag")
    data = event.get("data")
    data_object = data.get("object") if isinstance(data, dict) else None
    if not isinstance(data_object, dict):
        raise InvalidEventError("the event carries no data object")

    assert isinstance(event_id, str)
    subscription_id = (
        subscription_id_for(event_type, data_object) if event_type in HANDLED_EVENT_TYPES else None
    )
    return VerifiedEvent(
        event_id=event_id, event_type=event_type, livemode=livemode, subscription_id=subscription_id
    )
