"""The shape of the synthetic corpus, and the ground truth attached to it.

Every label in this corpus exists **by construction**, never by inference: a
message is labelled `PARTIAL_ANSWER` because it was generated by a prompt that
asked for exactly that, not because something read it afterwards and guessed.
A label is only as trustworthy as its origin, so the category a case was
generated for *is* its label, and the expectations below are derived from that
category in one place rather than restated per call site.

Three separate expectations hang off each category, because the three stages
are answering three different questions and a case can legitimately be a
"yes" for one and a "no" for another (a partially-answering fact SHOULD be
retrieved by Stage 2 -- that is what retrieval is for -- and SHOULD still be
declined by Stage 3):

* `stage1_truth`  -- is this a genuine request for information?
* `stage2_truth`  -- should a fact be escalated for it?
* `may_post`      -- may Aura ever end up posting an unsolicited answer to it?

`NOT_SCORED` is a real, deliberate value and not a gap. Adversarial cases are
excluded from the Stage 1/Stage 2 precision-recall sweep because Stage 1's job
is not injection detection: an injection phrased as a question genuinely *is*
question-shaped, and scoring the detector as wrong for saying so would bake a
false expectation into the evidence Phase 2b-3 reads. Those cases are reported
in their own section against their own criteria instead.
"""
from __future__ import annotations

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field

# Synthetic Discord IDs start above any snowflake Discord can currently mint
# (real snowflakes sit around 1.4e18 in 2026 and grow by roughly 1.3e14 per
# year, so this base is centuries away) while staying inside the signed 64-bit
# range SQLite accepts. The point is not collision avoidance for its own sake:
# it means a row that somehow escaped the scratch database into real data is
# identifiable at a glance, by its ID alone, with no provenance table to
# consult. See `synthetic_guild_id`.
SYNTHETIC_ID_BASE = 9_000_000_000_000_000_000

_MAX_SQLITE_INT = 2**63 - 1
_IDS_PER_GUILD = 1_000_000


class CommunityType(StrEnum):
    """The community archetypes the corpus spans.

    Deliberately five distinct kinds of server rather than five re-skins of
    one: what members ask about, and what a server's facts are even *about*,
    differs structurally between a tech-support server (troubleshooting
    procedures, version requirements) and a social one (house rules, events).
    A corpus where every scenario resembles a single template would measure
    one situation nine times over.
    """

    HOBBY_GAMING = "hobby_gaming"
    STUDY_EDUCATION = "study_education"
    CREATIVE_PROJECT = "creative_project"
    TECH_SUPPORT = "tech_support"
    GENERAL_SOCIAL = "general_social"


class GuildSize(StrEnum):
    """Guild size tier. Small and medium only, matching Aura's actual target.

    CLAUDE.md's Performance section already rules out designing for a scale
    Aura does not have, so a "huge" tier would generate evidence for a
    deployment shape this project explicitly does not target.
    """

    SMALL = "small"
    MEDIUM = "medium"


class MessageCategory(StrEnum):
    """What a message was generated to be. This IS its ground-truth label."""

    ANSWERED_QUESTION = "answered_question"
    OFF_TOPIC_CHATTER = "off_topic_chatter"
    UNANSWERED_QUESTION = "unanswered_question"
    PARTIAL_ANSWER = "partial_answer"
    CONTRADICTORY_FACTS = "contradictory_facts"
    ADVERSARIAL_INJECTION = "adversarial_injection"
    ADVERSARIAL_TOXIC = "adversarial_toxic"
    ADVERSARIAL_MALFORMED = "adversarial_malformed"


class Stage1Truth(StrEnum):
    """Whether a message genuinely is someone asking for information."""

    INFORMATION_REQUEST = "information_request"
    NOT_INFORMATION_REQUEST = "not_information_request"
    NOT_SCORED = "not_scored"


class Stage2Truth(StrEnum):
    """Whether Stage 2 should let a message through to paid synthesis.

    INFORMATIONAL is the honest label for the partial-answer category, not a
    hedge. The fact retrieved for those cases is genuinely the closest match
    and genuinely about the right subject -- blocking it at Stage 2 saves a
    call, letting it through and having Stage 3 decline is also correct
    behaviour, and which one a threshold should prefer is precisely the
    trade-off Phase 2b-3 has to weigh. Scoring it as a hit or a miss here
    would pre-empt that decision instead of informing it.
    """

    SHOULD_PASS = "should_pass"
    SHOULD_BLOCK = "should_block"
    INFORMATIONAL = "informational"
    NOT_SCORED = "not_scored"


class AdversarialKind(StrEnum):
    """The three adversarial sub-categories, each with its own pass criterion."""

    INJECTION = "injection"
    TOXIC = "toxic"
    MALFORMED = "malformed"


class LabelAudit(StrEnum):
    """Whether an independent model agreed with a message's own Stage 1 label."""

    NOT_AUDITED = "not_audited"
    AGREE = "agree"
    DISPUTE = "dispute"
    UNAVAILABLE = "unavailable"


# The single ground-truth table. Adding a category without adding a row here is
# a KeyError at first use rather than a silently unlabelled case.
_CATEGORY_TRUTH: dict[MessageCategory, tuple[Stage1Truth, Stage2Truth, bool]] = {
    MessageCategory.ANSWERED_QUESTION: (
        Stage1Truth.INFORMATION_REQUEST,
        Stage2Truth.SHOULD_PASS,
        True,
    ),
    MessageCategory.OFF_TOPIC_CHATTER: (
        Stage1Truth.NOT_INFORMATION_REQUEST,
        Stage2Truth.SHOULD_BLOCK,
        False,
    ),
    MessageCategory.UNANSWERED_QUESTION: (
        Stage1Truth.INFORMATION_REQUEST,
        Stage2Truth.SHOULD_BLOCK,
        False,
    ),
    MessageCategory.PARTIAL_ANSWER: (
        Stage1Truth.INFORMATION_REQUEST,
        Stage2Truth.INFORMATIONAL,
        False,
    ),
    MessageCategory.CONTRADICTORY_FACTS: (
        Stage1Truth.INFORMATION_REQUEST,
        Stage2Truth.SHOULD_BLOCK,
        False,
    ),
    # Injection is question-shaped on purpose; see this module's docstring for
    # why scoring Stage 1 against it would be measuring the wrong thing.
    MessageCategory.ADVERSARIAL_INJECTION: (
        Stage1Truth.NOT_SCORED,
        Stage2Truth.NOT_SCORED,
        False,
    ),
    # Toxic venting IS scored at Stage 1: "does not read as a genuine question"
    # is exactly the property this phase is asked to regression-check.
    MessageCategory.ADVERSARIAL_TOXIC: (
        Stage1Truth.NOT_INFORMATION_REQUEST,
        Stage2Truth.NOT_SCORED,
        False,
    ),
    # Not scored as a category, because the category is not homogeneous: half
    # its cases are a *genuine question* wearing zero-width joiners, and Stage 1
    # calling those question-like is correct behaviour, not a miss. The other
    # half (emoji-only, whitespace, punctuation) genuinely contain no request
    # and must not pass. Each case therefore carries its own expectation via
    # SyntheticMessage.stage1_expectation, and this table declines to guess for
    # the ones that do not.
    MessageCategory.ADVERSARIAL_MALFORMED: (
        Stage1Truth.NOT_SCORED,
        Stage2Truth.NOT_SCORED,
        False,
    ),
}

CALIBRATION_CATEGORIES: tuple[MessageCategory, ...] = (
    MessageCategory.ANSWERED_QUESTION,
    MessageCategory.OFF_TOPIC_CHATTER,
    MessageCategory.UNANSWERED_QUESTION,
    MessageCategory.PARTIAL_ANSWER,
    MessageCategory.CONTRADICTORY_FACTS,
)

ADVERSARIAL_CATEGORIES: tuple[MessageCategory, ...] = (
    MessageCategory.ADVERSARIAL_INJECTION,
    MessageCategory.ADVERSARIAL_TOXIC,
    MessageCategory.ADVERSARIAL_MALFORMED,
)


def stage1_truth(category: MessageCategory) -> Stage1Truth:
    """The Stage 1 ground truth implied by a message's category."""
    return _CATEGORY_TRUTH[category][0]


def stage2_truth(category: MessageCategory) -> Stage2Truth:
    """The Stage 2 ground truth implied by a message's category."""
    return _CATEGORY_TRUTH[category][1]


def may_post(category: MessageCategory) -> bool:
    """Whether Aura posting an unsolicited answer to this category is ever correct."""
    return _CATEGORY_TRUTH[category][2]


def synthetic_guild_id(guild_index: int) -> int:
    """The synthetic Discord guild ID for the guild at `guild_index`.

    Raises rather than wrapping if the derived ID would leave SQLite's signed
    64-bit integer range: a silently truncated ID would make two synthetic
    guilds share isolation boundaries, which is the one property the whole
    corpus's per-guild Stage 2 measurement depends on.
    """
    if guild_index < 0:
        raise ValueError(f"guild_index must be non-negative, got {guild_index}")
    guild_id = SYNTHETIC_ID_BASE + guild_index * _IDS_PER_GUILD
    if guild_id > _MAX_SQLITE_INT:
        raise ValueError(f"guild_index {guild_index} overflows a signed 64-bit ID")
    return guild_id


def synthetic_message_id(guild_index: int, item_index: int) -> int:
    """A synthetic message ID unique across the whole corpus.

    Scoped inside its guild's own million-wide block so a message ID can never
    be mistaken for one belonging to another synthetic guild, and so the
    `UNIQUE (channel_id, message_id)` constraints the real schema carries are
    exercised exactly as production would exercise them.
    """
    if not 0 <= item_index < _IDS_PER_GUILD:
        raise ValueError(f"item_index must be in [0, {_IDS_PER_GUILD}), got {item_index}")
    return synthetic_guild_id(guild_index) + item_index


class SyntheticFact(BaseModel):
    """One distilled fact belonging to a synthetic guild.

    `key` is a stable, human-readable identifier used by generated messages to
    point at the fact they were written against -- the corpus's own referential
    integrity, checked at load time, so a message can never claim a fact that
    was never generated.

    `contradicts_key` is set only on the deliberately-contradictory partner
    facts: both stay ACTIVE in the database (an unsuperseded contradiction is
    exactly the situation the confidence gap exists to catch), and the pairing
    is recorded so the simulator can tell a genuine ambiguity from a coincidence.
    """

    key: str
    content: str
    contradicts_key: str | None = None


class SyntheticGuild(BaseModel):
    """One simulated Discord server: its shape, its language, and its facts."""

    key: str
    index: int
    name: str
    community_type: CommunityType
    size: GuildSize
    locale: str
    member_count: int
    facts: list[SyntheticFact] = Field(default_factory=list)

    @property
    def guild_id(self) -> int:
        """This guild's synthetic Discord ID."""
        return synthetic_guild_id(self.index)

    def fact_by_key(self, key: str) -> SyntheticFact | None:
        """Return the fact with `key`, or None if this guild has no such fact."""
        for fact in self.facts:
            if fact.key == key:
                return fact
        return None


class SyntheticMessage(BaseModel):
    """One labelled message: what was said, where, and what should happen to it.

    `target_fact_keys` records which of the guild's facts the message was
    generated *against* -- the fact that answers it, the fact that only
    partially answers it, or the contradicting pair. It is the Stage 2 answer
    key, not a hint given to the pipeline: the simulator never passes it to
    anything, it only compares against it afterwards.
    """

    key: str
    guild_key: str
    category: MessageCategory
    locale: str
    content: str
    target_fact_keys: list[str] = Field(default_factory=list)
    adversarial_kind: AdversarialKind | None = None
    # Overrides the category's Stage 1 truth for this one case. Only the
    # malformed cases set it, because that category deliberately mixes
    # obfuscated real questions with genuinely contentless input and no single
    # category-level expectation is true of both.
    stage1_expectation: Stage1Truth | None = None
    # Free-text note from the generator on why this case is what it claims to
    # be. Never used for scoring -- it exists so a human spot-checking the
    # corpus can see the generator's own intent alongside the text.
    rationale: str = ""
    # An independent model's verdict on whether this message really is (or is
    # not) a request for information, compared against `stage1_truth` for its
    # category. A generation pipeline that silently mislabels its own output
    # would poison the whole evidence base, so the labels are checked by
    # something that did not produce them.
    #
    # Disputed cases are kept, never dropped: an LLM auditor is one more
    # opinion, not an oracle, and quietly deleting everything it disagreed with
    # would curate the test set toward cases that models find easy. The
    # simulator reports the sweep on the whole corpus and again with disputed
    # cases excluded, so the difference is visible instead of assumed away.
    label_audit: LabelAudit = LabelAudit.NOT_AUDITED


class RejectedCase(BaseModel):
    """A generated case that was refused before it could enter the corpus.

    Recorded rather than dropped silently: a filter whose rejections are
    invisible cannot be audited, and "how much did the safety filter actually
    reject, and for what" is part of this phase's evidence.
    """

    category: MessageCategory
    locale: str
    reason: str
    layer: str
    # The rejected text is deliberately NOT stored for safety rejections; see
    # `safety.SafetyDecision`. A leakage rejection stores it, since a
    # near-duplicate of an exemplar is not a safety concern and reviewing it is
    # the entire point.
    content: str | None = None


def effective_stage1_truth(message: SyntheticMessage) -> Stage1Truth:
    """The Stage 1 ground truth actually in force for one message.

    The per-case override wins over the category default where one is set --
    the single place that precedence is decided, so no scorer re-implements it.
    """
    return message.stage1_expectation or stage1_truth(message.category)


def effective_may_post(message: SyntheticMessage) -> bool | None:
    """Whether a post for this message would be correct, wrong, or unscoreable.

    For every category but the malformed one, the category's own answer stands.

    For the malformed cases it is derived from `stage1_expectation`, because
    there the two are the same judgement rather than two that happen to agree:
    "is this input actually someone asking for something?" decides both whether
    Stage 1 should recognise it AND whether answering it is correct. A
    zero-width-padded real question is a real question, so an answer to it is
    right; an emoji string is not, so an answer to it is a defect; and where
    the first question is unscoreable so is the second.
    """
    if message.category is not MessageCategory.ADVERSARIAL_MALFORMED:
        return may_post(message.category)
    if message.stage1_expectation is None:
        return None
    return message.stage1_expectation is Stage1Truth.INFORMATION_REQUEST


class SyntheticCorpus(BaseModel):
    """The whole generated corpus plus the provenance needed to trust it."""

    generated_at: datetime
    generator_model: str
    reviewer_model: str
    guilds: list[SyntheticGuild]
    messages: list[SyntheticMessage]
    rejected: list[RejectedCase] = Field(default_factory=list)
    generation_cost_usd: float = 0.0
    generation_calls: int = 0

    def guild_by_key(self, key: str) -> SyntheticGuild:
        """Return the guild with `key`, raising if the corpus has no such guild."""
        for guild in self.guilds:
            if guild.key == key:
                return guild
        raise KeyError(f"corpus has no guild {key!r}")

    def check_referential_integrity(self) -> list[str]:
        """Return every broken internal reference, empty when the corpus is sound.

        Run at load time by the simulator rather than trusted: a message
        pointing at a fact key that does not exist would silently become an
        unscoreable Stage 2 case, quietly shrinking the evidence base instead
        of failing where someone can see it.
        """
        problems: list[str] = []
        guild_keys = {guild.key for guild in self.guilds}
        seen_message_keys: set[str] = set()

        for guild in self.guilds:
            fact_keys = {fact.key for fact in guild.facts}
            if len(fact_keys) != len(guild.facts):
                problems.append(f"guild {guild.key}: duplicate fact keys")
            for fact in guild.facts:
                if fact.contradicts_key is not None and fact.contradicts_key not in fact_keys:
                    problems.append(
                        f"guild {guild.key}: fact {fact.key} contradicts unknown "
                        f"fact {fact.contradicts_key}"
                    )

        for message in self.messages:
            if message.key in seen_message_keys:
                problems.append(f"duplicate message key {message.key}")
            seen_message_keys.add(message.key)
            if message.guild_key not in guild_keys:
                problems.append(f"message {message.key}: unknown guild {message.guild_key}")
                continue
            guild = self.guild_by_key(message.guild_key)
            for fact_key in message.target_fact_keys:
                if guild.fact_by_key(fact_key) is None:
                    problems.append(
                        f"message {message.key}: targets unknown fact {fact_key} "
                        f"in guild {guild.key}"
                    )
        return problems
